name 'linux_basic'
maintainer 'harish'
maintainer_email 'harishkumarswamy@gmail.com'
license 'All rights reserved'
description 'Basic DevOps for single machine'
long_description 'harish repo'
providers 'execute[apt]'
source_url = 'https://github.com/harishsrs/chef-cookbooks' 
supports 'ubuntu'
version '1.2.3'
